In [5]:
import numpy as np
import math

In [12]:
a=np.arange(100).reshape(10,5,2)

In [8]:
print(a)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [20]:
for num in range(2,10):
    if num%2==0:
        print('found an even number',num)
        continue
    print('Found a odd number',num)

found an even number 2
Found a odd number 3
found an even number 4
Found a odd number 5
found an even number 6
Found a odd number 7
found an even number 8
Found a odd number 9


In [22]:
def fib(n):    # write Fibonacci series up to n
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


In [28]:
def add():
    a=5
    b=6
    sum=a+b
    return sum
val=add()
val

11

In [30]:
import pandas as pd

In [31]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [32]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [38]:
dates = pd.date_range("20200101", periods=6)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [39]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2020-01-01 -0.519604 -0.163192  1.247291  0.566881
2020-01-02 -0.276868  0.004345  0.117050  0.162444
2020-01-03 -0.149364 -0.029191  0.347846  0.217248
2020-01-04  2.170242 -1.478029 -0.147449  0.195083
2020-01-05 -0.302903 -0.047330 -0.086239 -0.330879
2020-01-06  0.315388 -1.661198 -0.083956  0.118248

In [46]:
def add(a,b,c):
    sum=a+b+c
    return sum
a=int(input('Enter the value od a'))
b=int(input('enter the value of b'))
c=int(input('enter the value of c'))
add(a,b,c)

Enter the value od a10
enter the value of b12
enter the value of c18


40

In [60]:
d = {'col1': [1, 2,3], 'col2': [3,np.nan,6]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1   3.0
1     2   NaN
2     3   6.0

In [76]:
import pandas as pd

In [82]:
Df1=pd.DataFrame(columns=['X1',"X2"])
X1=[2,4,6,8,9,5,'Jit']
X2=['man',3,5,6,7,9,1]
Df1['X1']=pd.Series[X1]
Df1['X1']=pd.Series[X2]
Df1

TypeError: 'type' object is not subscriptable

TypeError: 'type' object is not subscriptable

In [42]:
add(14,12,4)

30

In [44]:
add(12,45,48)

105

In [75]:
a=np.random.randn(2,3)
a

array([[ 0.74666575,  0.07362445,  1.68569242],
       [-1.26054682, -0.18071906, -0.40102998]])